name: Fetch latest YouTube video URL

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest URL
        id: fetch_video_url
        run: |
          if [ -f "./yt-dlp" ]; then
            # Get YouTube channel nickname from `accounts.conf`
            CHANNEL_NAME=$(sed "1q;d" data/accounts.conf)

            # Check if nickname exists. If not, default to YouTube
            if [ -z "${CHANNEL_NAME}" ]; then
              CHANNEL_NAME="youtube"
            fi

            # Extract @ char in case of declaration
            CHANNEL_NAME="${CHANNEL_NAME#@}"

            # Fetch for the latest video URL. If there is none, default to channel page.
            URL=$(./yt-dlp --playlist-items 1 --flat-playlist --print webpage_url "https://www.youtube.com/@${CHANNEL_NAME}/videos" 2>/dev/null || true)
            if [ -z "${URL}" ]; then
              URL="https://www.youtube.com/@${CHANNEL_NAME}"
            fi

            # Export the URL as an environment variable
            echo "LATEST_VIDEO_URL=${URL}" >> $GITHUB_ENV
          fi

      - name: Generate index.html
        id: generate_index
        env:
          URL: ${{ env.LATEST_VIDEO_URL }}
        run: |
          # Get page information from `page.conf`
          TITLE=$(sed "1q;d" data/page.conf)
          DESCRIPTION=$(sed "2q;d" data/page.conf)
          printf "<\!DOCTYPE html>\n<html>\n<head>\n\t<meta charset=\"UTF-8\">\n\t<title>${TITLE}</title>\n\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\n\t<script>\n\t\tasync function getLatestYouTubeURL()\n\t\t{\n\t\t\twindow.location.href = \"${URL}\";\n\t\t}\n\t\twindow.onload = getLatestYouTubeURL;\n\t</script>\n</head>\n<body>\n\t<p>${DESCRIPTION}</p>\n</body>\n</html>\n\n" > index.html

      - name: Commit changes
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git commit -m "index.html: Updated YouTube URL" || echo "No changes to commit"

      - name: Push changes
        id: push
        run: git push
